import { useLocation } from "react-router";

/**
 * The router state the submit flows hand to the confirmation pages.
 *
 * `enroleeNumber` is the proof: it is generated by the database during submission and only
 * reaches the router once the submit mutation has resolved, so its presence is what separates
 * "we really wrote this application" from "the browser arrived here some other way".
 */
export type SubmissionState = {
  academicYear: string;
  enroleeNumber: string;
};

/**
 * Reads the submission a confirmation page is meant to be celebrating, or `null` when the page
 * was reached without one.
 *
 * A confirmation page is an unconditional promise to the parent ("Application Received!"), so it
 * must not render on faith. Back/forward navigation replays a past success out of the History
 * API - a parent enrolling a second child can land on the confirmation for the first - and a
 * bookmarked or hand-typed URL carries no state at all. Both have to be turned away rather than
 * told an application is in.
 *
 * Reading `state` defensively also matters on its own: it is `null` for any navigation that
 * didn't set it, and destructuring that null used to throw, which the route's error boundary
 * turned into a full-page error.
 */
export function useSubmissionState(): SubmissionState | null {
  const { state } = useLocation();

  const submission = (state ?? null) as Partial<SubmissionState> | null;

  if (!submission?.enroleeNumber || !submission.academicYear) {
    return null;
  }

  return { academicYear: submission.academicYear, enroleeNumber: submission.enroleeNumber };
}
